spring:
  profiles:
    active: local
    include: oauth2, crypto, db, data, secret
  batch:
    job:
      name: ${job.name:NONE}
      enabled: false
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 20MB
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 1000

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
  main:
    lazy-initialization: true
  data:
    redis:
      host: ${redis.devHost}
  kafka:
    bootstrap-servers: localhost:${custom.kafka.devPort}
    host: localhost
    port: ${custom.kafka.devPort}
  redis:
    host: ${redis.devHost}
    port: ${redis.devPort}
#
#kafka:
#  host: "localhost:"
#  port: ${custom.kafka.devPort}

---

spring:
  profile:
    config:
      activate:
        on-profile: crypto
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: ${secret.jasypt.algorithm}
    pool-size: 2
    string-output-type: base64
    key-obtention-iterations: 100000
    password: ${secret.jasypt.password}

jwt:
  secret: ENC(JuKgHEVRxF4KNsrDCA5DPs99AsOaLbkLSmqVGbm1En8ahwd/S9QV8I+SrqeYwhMcH4dvFsOgfP5ug0MYuxpo5A==)
  access-expiration-time: 900000 # 15분 -> 15 * 60 * 1000
  refresh-expiration-time: 1296000000 # 15일 -> 15 * 24 * 60 * 60 * 1000

---

spring:
  config:
    activate:
      on-profile: oauth2

oauth:
  name-json: /src/main/resources/names/names.json
  kakao:
    client-id: ENC(/NVz3t1aoMGO4L9F9MI017vxf8KcHfo3y/+xMWKfUAg1LcGiqMY6l0NvNXXPjKJC)
    client-secret: ENC(+c7I7VG9cIym6iwPEnZKIzpkTVmhDB/SbHBy5RO2fGSse9r7pauDqfzRrSrvnmv1)
    redirect-uri: http://localhost:3000/accounts/login/process
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
    scope: account_email, profile_nickname
  naver:
    client-id: ENC(lPu7dZZ8/5Nw+58vtKCPkVqWFFOavr41eEQ4iTZHeAM=)
    client-secret: ENC(C3vESb/5wp0oAS5Xv0+31pE002otp/aN)
    redirect-uri: http://localhost:3000/accounts/login/process
    token-uri: https://nid.naver.com/oauth2.0/token
    user-info-uri: https://openapi.naver.com/v1/nid/me
    scope: email, nickname
  google:
    client-id: ENC(luscQ6r+mxP+gAP78vcRKcTijftTHz9VSVOuqedk3K7MgiXy9DnlY41iidg/hicV9TrwHw0l7qwrB6CBXJblOx0mOPYMAzovP8iy7ioZ8Bom1Ni/8nMFwg==)
    client-secret: ENC(jg1P3lhfBAokesMnvtuG5Kb0KIS3GIikIOfsNKztn3x67Qvhlt4iSbHbaMZFHXf+)
    redirect-uri: http://localhost:3000/accounts/login/process
    scope: email, profile